server:
  port: 8088

spring:
  application:
    name: config-service
  cloud:
    config:
      server: 
        git: 
          uri: https://github.com/java-spring-microservice/server-config
          default-label: main